### ISSUE TITLE
Eingabeformat "Liste" akzeptiert keine Bestriche für Kommazahlen

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#11]
Wählt man als Eingabeformat Liste aus und will Kommazahlen eingeben, werden diese nur akzeptiert, wenn man als Trennzeichen einen Punkt wählt. Bei Eingabe von Beistrichen erhält man die Fehlermeldung "Die Anzahl der eingegebenen Werte ist invalid. Notiz: Bitte lassen Sie ein Feld leer (zB leere Zeile in Listeneingabe), falls keine Daten vorliegen"

Siehe hierzu auch Fix für manuell Eingabe: https://github.com/meisterluk/datenlandkarte/commit/07a68625d2652ca4b32915a8ce47717cb3f74017

**Comment by meisterluk** [comment]
Dieses Problem wurde in v2 behoben. Sollte jetzt funktionieren.
