### ISSUE TITLE
Gemeinden Österreich - Konfig 

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#17]
Bei Auswahl von "Gemeinden Österreich"  werden nicht alle Ebenen des Templates angezeigt (Albeck bis Sankt Anton im Montafon statt Eisenstadt bis Wien 23.,Liesing)

Lt. global.php werden diese Werte automatisch befüllt:

2 => array(
                        'name' => 'Gemeinden Österreichs',
                        'filename' => 'gmaustria',

```
                    // this is automatically filled
                )
```

Mit dem Tool trans.php könnte ich die 2357 Werte manuell in der global.php eintragen - dies würde jedoch das File sehr groß machen. Gibt es eine Möglichkeit, dies beim automatischen auslesen zu fixen?

**Comment by meisterluk** [comment]
Ist mir unklar, wie das gemeint ist.

Unter "Datenlandkarten erstellen" > Vorlage "Europa / Österreich / Föderale Ebene / Gemeinden Österreichs". Es werden alle Bezirke angezeigt, die in der global.php vorkommen. Von "Eisenstadt" bis "2319".

**Comment by seyfro** [comment]
OK - nun werden alle angezeigt.
