### ISSUE TITLE
Eingabe in Listenform funktioniert nicht

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#18]
wählt man bei Erweiterte Optionen "Liste" aus und gibt dann zB für die Bundesländer Österreichs folgende Liste (mit Standardtrennzeichen \n) ein,

1
2
3
4
5
6
7
8
9

erhält man folgende Fehlermeldung: Eine Graphik konnte nicht erzeugt werden. Habs auch mit einer größeren Liste (Zählbezirke Wien) versucht - selbe Fehlermeldung.

**Comment by meisterluk** [comment]
Sollte bei meisterluk/datenlandkarte@a461b6c65f61731e675a gefixt worden sein. Die genannten Tests funktionieren jetzt. Sollten keine Probleme mehr auftreten, wird dieses Issue in 1 Woche geschlossen.

**Comment by seyfro** [comment]
Funktioniert nun - danke!
