### ISSUE TITLE
Info-links target nicht auf "_blank" gesetzt bei Datenlandkarte erstellen

### ISSUE THREAD

**Issue by PeterTheOne** [meisterluk/datenlandkarte#24]
Manche Links zu Zusatzinformationen werden im gleichen "frameset" geladen, dass könnte unerfahrene Benutzer verwirren. Also statt `<a href="http://creativecommons.org/licenses/by-sa/3.0/at/">CC By-SA</a>` `<a target="_blank" href="http://creativecommons.org/licenses/by-sa/3.0/at/">CC By-SA</a>`.

Link liste:
- `<a href="http://creativecommons.org/licenses/by-sa/3.0/at/">CC By-SA</a>`
- `<a href="./vorlagen">Vorlagen, an denen wir arbeiten</a>`

**Comment by meisterluk** [comment]
Das W3C ist sicher etwas unsicher, wie es mit dem target Attribut weitergeht. Normalerweise sollte es dem User überlassen werden, wie er eine Seite öffnet (Mittlere vs linke Maustaste). Mit den TUIs weiß man aber nicht, wie man diesbezüglich weiterverfährt.

Aber danke für den Hinweis. Ein UI-Test für Konsistenz wäre sowieso angebracht :-)
