### ISSUE TITLE
Probleme mit Skala bei Daten mit Nachkommastellen?

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#3]
Visualisier mal bitte folgenden Europa-Array - sind die F&E-Ausgaben in % des BIP; Skala geht nur von 0-1 - hab bei der Eingabe sowohl 0.5 als auch 0,5 probiert - keine Auswirkung - Bug?

{"Albanien":true,"Andorra":true,"Belgien":1.96,"Bosnien und Herzegowina":true,"Bulgarien":0,"D\u00e4nemark":0,"Deutschland":2.82,"Estland":1.42,"Finnland":3.96,"Frankreich":2.21,"Griechenland":true,"Irland":1.77,"Island":true,"Italien":1.27,"Kasachstan":true,"Kosovo":true,"Kroatien":0,"Lettland":0,"Liechtenstein":true,"Litauen":0,"Luxemburg":1.68,"Malta":0,"Mazedonien":true,"Moldawien":true,"Monaco":true,"Montenegro":true,"Niederlande":1.84,"Norwegen":1.8,"\u00d6sterreich":2.75,"Polen":0,"Portugal":1.66,"Rum\u00e4nien":0,"Russland":true,"San Marino":true,"Schweden":3.6,"Schweiz":true,"Serbien":true,"Slowakei":true,"Slowenien":true,"Spanien":1.38,"Tschechien":1.53,"T\u00fcrkei":true,"Ukraine":true,"Ungarn":1.15,"Vatikanstadt":true,"Vereinigtes K\u00f6nigreich":1.87,"Wei\u00dfrussland":true}

**Comment by seyfro** [comment]
Selbes Problem tritt bei absoluten Zahlen auf - siehe Bevölkerungsstatistik Europa absolut: {"Albanien":true,"Andorra":true,"Belgien":0,"Bosnien und Herzegowina":true,"Bulgarien":0,"D\u00e4nemark":5534738,"Deutschland":0,"Estland":0,"Finnland":5351427,"Frankreich":0,"Griechenland":0,"Irland":4467854,"Island":0,"Italien":0,"Kasachstan":true,"Kosovo":true,"Kroatien":4425747,"Lettland":2248374,"Liechtenstein":35894,"Litauen":0,"Luxemburg":0,"Malta":0,"Mazedonien":0,"Moldawien":true,"Monaco":true,"Montenegro":632922,"Niederlande":16574989,"Norwegen":4858199,"\u00d6sterreich":0,"Polen":38167329,"Portugal":0,"Rum\u00e4nien":21462186,"Russland":true,"San Marino":true,"Schweden":0,"Schweiz":0,"Serbien":true,"Slowakei":5424925,"Slowenien":0,"Spanien":0,"Tschechien":0,"T\u00fcrkei":72561312,"Ukraine":true,"Ungarn":0,"Vatikanstadt":true,"Vereinigtes K\u00f6nigreich":0,"Wei\u00dfrussland":true}

**Comment by seyfro** [comment]
Eigenartig ist, dass einmal bei einem Leerwert 0 und einmal true steht. Bei der Eingabe der Daten hab ich das Feld freigelassen...

**Comment by meisterluk** [comment]
1. true ist kein valider Eingabewert. Keine Werte vorhanden bedeutet Feld auslassen.
2. Bei Europa befand sich ein Bug.
   https://github.com/meisterluk/datenlandkarte/commit/f73400b8e8f2f8fbb05d2d3fead62ac9ee00209d

Bitte nochmals testen. Sollte jetzt passen.
{
    "base" : [ "europe", "l" ], "colors" : 10, "data" : {"Belgien":1.96,"Bulgarien":0,"D\u00e4nemark":0,"Deutschland":2.82,"Estland":1.42,"Finnland":3.96,"Frankreich":2.21,"Irland":1.77,"Italien":1.27,"Kroatien":0,"Lettland":0,"Litauen":0,"Luxemburg":1.68,"Malta":0,"Niederlande":1.84,"Norwegen":1.8,"\u00d6sterreich":2.75,"Polen":0,"Portugal":1.66,"Rum\u00e4nien":0,"Schweden":3.6,"Spanien":1.38,"Tschechien":1.53,"Ungarn":1.15,"Vereinigtes K\u00f6nigreich":1.87},
    "dec" : 3, "grad" : 2, "subtitle" : "Untertitel", "title" : "Haupttitel"
}

**Comment by seyfro** [comment]
gefixed - danke!
