### ISSUE TITLE
Falsche Einfärbung bei leeren Werten

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#4]
Beispiel: 
{"Burgenland":1.1,"K\u00e4rnten":1.2,"Nieder\u00f6sterreich":1.3,"Ober\u00f6sterreich":1.4,"Salzburg":1.5,"Steiermark":1.6,"Tirol":1.7,"Vorarlberg":true,"Wien":1.8}

Vorarlberg müßte weiß sein, ist aber rot

**Comment by meisterluk** [comment]
true ist kein valider Wert. API wurde verändert.

http://www.datamaps.eu/tool/api.php?q={%0D%0A++++%22base%22+%3A+[+%22austria%22%2C+%22bl%22+]%2C%0D%0A++++%22colors%22+%3A+10%2C%0D%0A++++%22data%22+%3A+{%22Burgenland%22%3A1.1%2C%22K\u00e4rnten%22%3A1.2%2C%22Nieder\u00f6sterreich%22%3A1.3%2C%22Ober\u00f6sterreich%22%3A1.4%2C%22Salzburg%22%3A1.5%2C%22Steiermark%22%3A1.6%2C%22Tirol%22%3A1.7%2C%22Wien%22%3A1.8}%2C%0D%0A++++%22dec%22+%3A+3%2C%0D%0A++++%22grad%22+%3A+2%2C%0D%0A++++%22subtitle%22+%3A+%22Untertitel%22%2C%0D%0A++++%22title%22+%3A+%22Haupttitel%22%0D%0A}
