### ISSUE TITLE
Falsche Basisfarbe

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#5]
leere werden bei nachfolgendem Array rot angezeigt & nicht weiß:

{"Albanien":2,"Andorra":3,"Belgien":4,"Bosnien und Herzegowina":5,"Bulgarien":6,"D\u00e4nemark":true,"Deutschland":true,"Estland":true,"Finnland":true,"Frankreich":true,"Griechenland":true,"Irland":true,"Island":true,"Italien":true,"Kasachstan":true,"Kosovo":true,"Kroatien":true,"Lettland":true,"Liechtenstein":true,"Litauen":true,"Luxemburg":true,"Malta":true,"Mazedonien":true,"Moldawien":true,"Monaco":true,"Montenegro":true,"Niederlande":true,"Norwegen":true,"\u00d6sterreich":true,"Polen":true,"Portugal":true,"Rum\u00e4nien":true,"Russland":true,"San Marino":true,"Schweden":true,"Schweiz":true,"Serbien":true,"Slowakei":true,"Slowenien":true,"Spanien":true,"Tschechien":true,"T\u00fcrkei":true,"Ukraine":true,"Ungarn":true,"Vatikanstadt":true,"Vereinigtes K\u00f6nigreich":true,"Wei\u00dfrussland":true}

**Comment by meisterluk** [comment]
Dieses JSON-Objekt stellt keine korrekt Anfrage dar. Zur Zeit des Bugreports war die Implementierung auch noch nicht stabil. Deshalb betrachte ich diesen Bugreport als deprecated.
