### ISSUE TITLE
Eingabe in Listenform wird bei Back-Button gelöscht.

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#7]
Weiß nicht, ob dies ein Bug im Sinne der Applikation ist, send ihn dir trotzdem mal:

erstellt man eine Infografik mit Typ manuell, kann man auf der Vorschauseite den Link "Parameter ändern und Grafik neu erstellen" anklicken (=javascript:back();) und man gelangt wieder zum Eingabeformular wo die Werte noch drinnen stehen.

Hat man die Grafik jedoch mit dem Typ Liste erstellt und klickt bei der Vorschau auf "Parameter ändern und Grafik neu erstellen", kommt man zur Eingabeseite zurück und die Liste ist nicht mehr ausgewählt und Werte gelöscht.

**Comment by meisterluk** [comment]
Jap, ist mir bekannt. Leider etwas ungenau formuliert, aber das ist mit der Zeile 19 in der README gemeint. Leider aktuell ideenlos, woran es genau liegt, aber ich werde es bei Gelegenheit fixen.

https://github.com/meisterluk/datenlandkarte/blob/master/README#L19

**Comment by seyfro** [comment]
Noch eins, das mir hier aufgefallen ist: wählt man eine Vorlage auf 3. Ebene aus (zB Bezirke Wien), wählt bei Eingabe manuell aus, erstellt eine Vorschau und klickt dann auf Parameter ändern, werden bei der Eingabeseite wieder die Daten für die Standardauswahl (Bundesländer) angezeigt und die bisher eingegebenen Werte sind verschwunden.

**Comment by meisterluk** [comment]
Wurde in der Version 2 gefixt.
