### ISSUE TITLE
Werte zwischen 0 und 1 werden nicht als Zahl erkannt

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#8]
## Rückmeldung eines Users:

ich hab mal ein wenig gespielt mit den Datenlandkarten, auch weil wir sie in unserer aktuellen Rubrik "webwatch" vorstellen.
Kleiner Bug:
Das Eingabeformular akzeptiert werte wischen 0 und 1 nicht als Zahl.
das ist vor allem nötig, wenn man niederschwellige Prozentwerte wie die Forschungsquote des Burgenlandes darstellen will. Die ist nämlich 0,6 und das hat er nicht ienlesen wollen.
## Beste Grüße und weiter viel Erfolg damit, sehr feine Sache.

Habs mit 0,1 bis 0,9 und 0.1 bis 0.9 probiert - es kommt jedesmal beim Erstellen die Fehlermeldung "Einer der eingegebenen Werte ist keine Zahl"

**Comment by meisterluk** [comment]
Thanks.

Has been debugged in 
https://github.com/meisterluk/datenlandkarte/commit/b1b1d3c65ce81f3592c868a8baf9de7ccbc82616
