### ISSUE TITLE
Google Translation Integration: Auswahl funktioniert nicht

### ISSUE THREAD

**Issue by seyfro** [meisterluk/datenlandkarte#9]
Um DataMaps.eu in mehreren Sprachen anbieten zu können, habe ich ein Google Translate-Plugin integriert (Klick auf Sprache in Sidebar, zB http://www.datamaps.eu/en/). Manuelles Übersetzen für verschiedene Sprachen wie ursprünglich angedacht, ist von den Ressourcen her derzeit nicht zu bewältigen, außerdem könnten wir sicher nie soviele Sprachen anbieten wie z.B. Google Translate.

Klickt man im Wordpress-Framework auf "Datamap create", wird das Eingabeformular mit der voreingestellten Erstauswahl "Austrian states" richtig angezeigt und man kann auch eine Infografik erstellen. Will man jedoch auf eine andere Vorlage wechseln, werden die Keys nicht im Formular angezeigt. 

Die Ergebnis/Vorschauseite ist dann wieder in deutsch - was aber denke ich kein Problem sein sollte. Im Endeffekt gehts mir darum, dass das Eingabeformular funktioniert.

**Comment by seyfro** [comment]
Link für Beispielübersetzung: http://translate.google.com/translate?hl=en&sl=de&tl=en&u=http%3A%2F%2Fwww.datamaps.eu

Hab ein anderes Übersetzungstool installiert, damit wir keine Unnötigen Aufwände produzieren - dieses ist zwar nicht so komfortabel wie das erste, weil jede Seite einzeln zum Übersetzen ausgewählt werden muss. Dafür funktioniert bei diesem auch die Auswahl der Vorlagen auf der Erstellen-Seite.

**Comment by meisterluk** [comment]
Soweit ich es verstehe, ist das Problem damit gelöst. Sonst bitte per Email.
